import { createClient } from '@/lib/supabase/server';
import { requireRole } from '@/lib/auth/guards';
import RecordManager, { type FieldDef } from '@/components/admin/RecordManager';

export default async function AdminDistrictsPage() {
  await requireRole('ADMIN');
  const { data } = await createClient().from('districts').select('*').order('district_code').limit(500);

  const fields: FieldDef[] = [
    { key: 'district_code', label: 'District code', required: true, help: 'Format: IL-05, AK-AL.' },
    { key: 'state_code', label: 'State code', required: true },
    { key: 'state_name', label: 'State name', required: true },
    { key: 'district_number', label: 'District number', required: true, help: 'Two digits, or AL for at-large.' },
    { key: 'population', label: 'Population', type: 'number' },
    { key: 'voting_age_population', label: 'Voting age population', type: 'number' },
    { key: 'median_household_income', label: 'Median household income', type: 'number' },
    { key: 'urban_rural', label: 'Classification', type: 'select',
      options: ['urban', 'suburban', 'rural', 'mixed'].map((v) => ({ value: v, label: v })) },
    { key: 'house_member', label: 'Current U.S. House member' },
    { key: 'house_member_party', label: 'Party' },
    { key: 'house_member_url', label: 'Official website' },
    { key: 'house_member_phone', label: 'Washington office phone' },
    { key: 'house_member_office', label: 'Office room' },
    { key: 'recent_turnout_pct', label: 'Recent turnout (%)', type: 'number' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
    { key: 'last_updated', label: 'Last updated', type: 'date' },
  ];

  return (
    <RecordManager
      table="districts"
      title="Districts"
      intro="District records. Members and their contact details are generated by npm run data:fetch from public-domain congressional records, so hand edits here are overwritten on the next run. Geography lives in public/data/districts.geojson and is replaced by npm run map:fetch — editing these rows never touches the map."
      rows={(data as Record<string, unknown>[]) ?? []}
      fields={fields}
      pk="district_code"
      columns={[
        { key: 'district_code', label: 'Code' },
        { key: 'state_name', label: 'State' },
        { key: 'house_member', label: 'House member' },
        { key: 'last_updated', label: 'Updated' },
      ]}
      empty={{ title: 'No district records', body: 'Add districts here, or load supabase/seed.sql for examples.' }}
    />
  );
}
